'use strict'

const { Router } = require('express')
const router = Router()

const evaluacionesRoutes = require('./evaluacionesRoutes')
const calculusRoutes = require('./calculusRoutes')
const userRoutes = require('./userRoutes')
const taskTypesRoutes = require('./taskTypesRoutes')
const taskRoutes = require('./taskRoutes')
const generalTasksRoutes = require('./generalTaskRoutes')
const specificTasksRoutes = require('./specificTaskRoutes')
const absencesTasksRoutes = require('./absencesTaskRoutes')
const profileRolesRoutes = require('./profileRolesRoutes')
const unitProfileRoutes = require('./unitProfileRoutes')
const configuracionesRoutes = require('./configuracionesRoutes')
const festivosRoutes = require('./festivosRoutes')
const departamentProfileRoutes = require('./departamentProfileRoutes')
const serviceProfileRoutes = require('./serviceProfileRoutes')
const subdirectorateProfileRoutes = require('./subdirectorateProfileRoutes')
const profilesRoutes = require('./profileRoutes')
const permissionsRoutes = require('./permissionRoutes')
const jobPositionsRoutes = require('./jobPositionRoutes')
const positionsPermissionRoutes = require('./positionPermissionRoutes')
const jobProfilesRoutes = require('./jobProfilesRoutes')
const profileTasksRoutes = require('./profileTaskRoutes')
const teamWorksRoutes = require('./teamsWorkRoutes')
const activitiesRoutes = require('./activitiesRoutes')
const ordOrExtOtherTasksRoutes = require('./ordOrExtOtherTaskRoutes')
const absencesObjetivesRoutes = require('./absencesObjetivesRoutes')
const generalObjetivesRoutes = require('./generalObjetivesRotes')
const specificsObjetivesRoutes = require('./specificObjetivesRoutes')
const ordExtOtherObjetivesRoutes = require('./ordExtOtherObjetivesRoutes')
const misObjetivosRoutes = require('./misObjetivosRoutes')
const entriesRoutes = require('./entriesRoutes')
const difficultiesRoutes = require('./difficultiesRoutes')
const tasksSharedRoutes = require('./tasksSharedRoutes')
const acumulativesTasksRoutes = require('./acumulativesTasksRoutes')
const dashboardRoutes = require('./dashboardRoutes')

router.use('/evaluaciones', evaluacionesRoutes)
router.use('/calculos', calculusRoutes)
router.use('/users', userRoutes)
router.use('/tipostareas', taskTypesRoutes)
router.use('/tareas', taskRoutes)
router.use('/tareasgenerales', generalTasksRoutes)
router.use('/tareasespecificas', specificTasksRoutes)
router.use('/tareasausencias', absencesTasksRoutes)
router.use('/perfilroles', profileRolesRoutes)
router.use('/perfilunidades', unitProfileRoutes)
router.use('/configuraciones', configuracionesRoutes)
router.use('/festivos', festivosRoutes)
router.use('/perfildepartamentos', departamentProfileRoutes)
router.use('/perfilservicios', serviceProfileRoutes)
router.use('/perfilsubdirecciones', subdirectorateProfileRoutes)
router.use('/perfiles', profilesRoutes)
router.use('/permisos', permissionsRoutes)
router.use('/puestostrabajo', jobPositionsRoutes)
router.use('/permisospuesto', positionsPermissionRoutes)
router.use('/perfilespuesto', jobProfilesRoutes)
router.use('/tareasperfil', profileTasksRoutes)
router.use('/equipostrabajo', teamWorksRoutes)
router.use('/tareasordextotras', ordOrExtOtherTasksRoutes)
router.use('/actividades', activitiesRoutes)
router.use('/objetivosausencias', absencesObjetivesRoutes)
router.use('/objetivosgenerales', generalObjetivesRoutes)
router.use('/objetivosespecificos', specificsObjetivesRoutes)
router.use('/objetivosordextotros', ordExtOtherObjetivesRoutes)
router.use('/misObjetivos', misObjetivosRoutes)
router.use('/entradas', entriesRoutes)
router.use('/dificultades', difficultiesRoutes)
router.use('/compartidas', tasksSharedRoutes)
router.use('/acumulativas', acumulativesTasksRoutes)
router.use('/cuadromandos', dashboardRoutes)

module.exports = router
