'use strict'

const FIELDS_IMAGE = 'images'
const FIELDS_SIMPLE_NOTE = 'simpleNoteFile'
const FIELDS_OWNERS_STATUTES = 'ownersStatutesFile'
const FIELDS_BLUEPRINT = 'blueprintFile'

const FIELDS_NAMES = [FIELDS_IMAGE, FIELDS_SIMPLE_NOTE, FIELDS_OWNERS_STATUTES, FIELDS_BLUEPRINT]

module.exports = {
  FIELDS_IMAGE,
  FIELDS_SIMPLE_NOTE,
  FIELDS_OWNERS_STATUTES,
  FIELDS_BLUEPRINT,
  FIELDS_NAMES,
}
